apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: ${ namespace }
  labels:
    app: keycloak
spec:
  ports:
    - protocol: TCP
      port: ${ backend_port }
      targetPort: http
      name: http
  selector:
    app: keycloak
  type: ClusterIP
