apiVersion: v1
kind: Service
metadata:
  name: ${ app.name }
  namespace: ${ app.namespace }
  labels:
    app: ${ app.name }
spec:
  ports:
    - protocol: TCP
      port: ${ app.backend.port }
      targetPort: http
      name: http
  selector:
    app: ${ app.name }
  type: ClusterIP
