name: Apply Workload Deployment
on:
  push:
    branches:
      - 'deployment/**'

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  parse-environment:
    name: Parse Environment
    runs-on: self-hosted
    outputs:
      environment: ${{ steps.get-branch-suffix.outputs.environment }}
    steps:
      - name: Extract deployment branch suffix
        id: get-branch-suffix
        run: |
          branch=${{ github.ref_name }}
          echo "environment=${branch#deployment/}" >> $GITHUB_OUTPUT
  get-pre-merge-sha:
    name: Get Pre-merge SHA
    runs-on: self-hosted
    outputs:
      sha: ${{ steps.get-sha.outputs.sha }}
    steps:
      - name: Get SHA
        id: get-sha
        run: |
          sha=$(jq -r '.commits[-2].id' "$GITHUB_EVENT_PATH")
          echo "sha=$sha" >> "$GITHUB_OUTPUT"
          echo "Pre-merge SHA: $sha"
  terraform-apply:
    name: Terraform Apply
    uses: $/.github/workflows/tf-apply.yml
    needs: [parse-environment, get-pre-merge-sha]
    with:
      environment: ${{ needs.parse-environment.outputs.environment }}
      storage_account_container_name: workload
      sha: ${{ needs.get-pre-merge-sha.outputs.sha }}
      working_dir: "./workload"
    secrets: inherit
