name: Terraform Apply
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    outputs:
      branch_suffix:
        value: ${{ steps.get-branch-suffix.outputs.branch_suffix }}
jobs:
  get-branch-suffix:
    runs-on: self-hosted
    outputs:
      branch_suffix: ${{ steps.get-branch-suffix.outputs.branch_suffix }}
    steps:
      - name: Extract branch suffix
        id: get-branch-suffix
        run: echo "branch_suffix=${${{inputs.branch}}#deployment/}" >> $GITHUB_OUTPUT
