name: Deploy Pushed Changes

on:
  push:
    branches:
      - 'deployment/**'

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  get-environment:
    uses: thompsonbear/homelab/.github/workflows/deployment-branch-suffix.yml@main
    with:
      branch: ${{ github.ref_name }}
  platform:
    uses: thompsonbear/homelab/.github/workflows/tf-apply.yml@main
    needs: get-environment
    with:
      environment: ${{ needs.get-environment.outputs.branch_suffix }}
      storage_account_container_name: platform
      sha: ${{ github.event.pull_request.head.sha }}
      working_dir: "./platform"
    secrets: inherit
  workload:
    uses: thompsonbear/homelab/.github/workflows/tf-apply.yml@main
    needs: platform
    with:
      environment: ${{ needs.get-environment.outputs.branch_suffix }}
      storage_account_container_name: workload
      sha: ${{ github.event.pull_request.head.sha }}
      working_dir: "./workload"
    secrets: inherit
