name: Destroy Deployment
on:
  delete:

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  parse-environment:
    name: Parse Environment
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'deployment/')
    runs-on: self-hosted
    outputs:
      environment: ${{ steps.get-branch-suffix.outputs.environment }}
    steps:
      - name: Extract deployment branch suffix
        id: get-branch-suffix
        run: |
          branch=${{ github.event.ref }}
          echo "environment=${branch#deployment/}" >> $GITHUB_OUTPUT
  destroy-workload:
    name: Destroy Workload
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'deployment/')
    uses: thompsonbear/homelab/.github/workflows/tf-destroy.yml@main
    needs: parse-environment
    with:
      environment: ${{ needs.parse-environment.outputs.environment }}
      storage_account_container_name: workload
      working_dir: "./workload"
    secrets: inherit
  destroy-platform:
    name: Destroy Platform
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'deployment/')
    uses: thompsonbear/homelab/.github/workflows/tf-destroy.yml@main
    needs: [parse-environment, workload]
    with:
      environment: ${{ needs.parse-environment.outputs.environment }}
      storage_account_container_name: platform
      working_dir: "./platform"
    secrets: inherit
