name: Handle PR Merge
on:
  pull_request:
    branches:
      - prod
      - staging
    types:
      - closed

jobs:
  apply-platform:
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      packages: read
      id-token: write
    uses: thompsonbear/homelab/.github/workflows/tf-apply.yml@prod
    with:
      environment: ${{ github.base_ref }}
      storage_account_container_name: platform
      sha: ${{ github.sha }}
      working_dir: "./platform"
    secrets: inherit

  # apply-workload:
  #   if: github.event.pull_request.merged == true
  #   uses: thompsonbear/homelab/.github/workflows/tf-apply.yml@prod
  #   with:
  #     environment: ${{ github.base_ref }}
  #     storage_account_container_name: workload
  #     sha: ${{ github.sha }}
  #     working_dir: "./workload"
