name: Terraform Destroy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      storage_account_container_name:
        required: true
        type: string
      working_dir:
        required: true
        type: string

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  terraform-destroy:
    environment: ${{ inputs.environment }}
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ inputs.working_dir }}
    env:
      ARM_USE_AZUREAD: "true"
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_az_key_vault_name: ${{ secrets.TF_VAR_AZ_KEY_VAULT_NAME }}
      TF_VAR_az_key_vault_rg: ${{ secrets.TF_VAR_AZ_KEY_VAULT_RG }}
      TF_VAR_network: ${{ secrets.TF_VAR_NETWORK }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Init
        shell: bash
        run: |
          terraform init \
            -backend-config="storage_account_name=${{ secrets.AZ_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ inputs.storage_account_container_name }}" \
            -backend-config="key=${{ inputs.environment }}.terraform.tfstate"

      - name: Terraform Destroy
        shell: bash
        run: |
          terraform destroy -auto-approve

      - name: Cleanup State/Plan Blobs
        shell: bash
        run: |
          az storage blob delete-batch \
            --account-name ${{ secrets.AZ_STORAGE_ACCOUNT_NAME }} \
            --source ${{ inputs.storage_account_container_name }} \
            --pattern "tfplan-${{ inputs.environment }}*"
          az storage blob delete \
            --account-name ${{ secrets.AZ_STORAGE_ACCOUNT_NAME }} \
            --container-name ${{ inputs.storage_account_container_name }} \
            --name ${{ inputs.environment }}.terraform.tfstate
